global using NUnit.Framework;
global using Microsoft.EntityFrameworkCore;
global using Moq;
global using Moq.EntityFrameworkCore;
global using MSt_Postcode_API.Domain.Constants;
global using MSt_Postcode_API.Domain.Entities;
global using MSt_Postcode_API.Domain.Entities.Mappers;
global using MSt_Postcode_API.Infrastructure.Data;
global using MSt_Postcode_API.Infrastructure.Services;
